<?php

namespace Tests\Feature;

use App\Models\Account;
use App\Models\User;
use Database\Seeders\AccountSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class TransactionApiTest extends TestCase
{
    use RefreshDatabase;

    protected User $user;
    protected Account $cashAccount;
    protected Account $expenseAccount;
    protected Account $revenueAccount;

    protected function setUp(): void
    {
        parent::setUp();

        // 1. Run AccountSeeder to seed Chart of Accounts
        $this->seed(AccountSeeder::class);

        // 2. Setup default Accounts reference
        $this->cashAccount = Account::where('code', '1101')->first(); // Kas Utama
        $this->expenseAccount = Account::where('code', '5103')->first(); // Beban Server & Software
        $this->revenueAccount = Account::where('code', '4101')->first(); // Pendapatan Utama

        // 3. Create a test user
        $this->user = User::factory()->create();
    }

    /**
     * Test user authentication endpoints.
     */
    public function test_user_can_login_and_access_protected_routes(): void
    {
        $response = $this->postJson('/api/login', [
            'email' => $this->user->email,
            'password' => 'password', // Default password generated by factory
        ]);

        $response->assertStatus(200)
            ->assertJsonStructure([
                'access_token',
                'token_type',
                'user',
            ]);

        $token = $response->json('access_token');

        // Test fetching user profile using the token
        $profileResponse = $this->getJson('/api/user', [
            'Authorization' => 'Bearer ' . $token,
        ]);

        $profileResponse->assertStatus(200)
            ->assertJsonPath('user.email', $this->user->email);
    }

    /**
     * Test fetching list of Chart of Accounts.
     */
    public function test_authenticated_user_can_fetch_accounts(): void
    {
        $response = $this->actingAs($this->user)->getJson('/api/accounts');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'data' => [
                    '*' => ['id', 'code', 'name', 'type'],
                ],
            ]);

        $this->assertCount(13, $response->json('data'));
    }

    /**
     * Test creating a Cash Out (pengeluaran) transaction with file upload.
     */
    public function test_user_can_create_cash_out_transaction_with_receipt(): void
    {
        Storage::fake('public');

        $receipt = UploadedFile::fake()->image('invoice.jpg', 500, 500);

        $payload = [
            'type' => 'out',
            'amount' => 150000.00,
            'account_id' => $this->expenseAccount->id, // Debiting Expense
            'payment_account_id' => $this->cashAccount->id, // Crediting Kas Utama
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'Pembayaran hosting bulanan Vercel',
            'receipt' => $receipt,
        ];

        $response = $this->actingAs($this->user)->postJson('/api/transactions', $payload);

        $response->assertStatus(201)
            ->assertJsonPath('message', 'Transaction saved successfully.')
            ->assertJsonStructure([
                'data' => [
                    'id',
                    'transaction_number',
                    'transaction_date',
                    'description',
                    'journal_entries',
                    'attachments',
                ]
            ]);

        // Assert transaction header exists
        $this->assertDatabaseHas('transactions', [
            'description' => 'Pembayaran hosting bulanan Vercel',
            'created_by' => $this->user->id,
        ]);

        // Assert double-entry journal entries exist
        $transactionId = $response->json('data.id');

        $this->assertDatabaseHas('journal_entries', [
            'transaction_id' => $transactionId,
            'account_id' => $this->expenseAccount->id,
            'type' => 'debit',
            'amount' => '150000.00',
        ]);

        $this->assertDatabaseHas('journal_entries', [
            'transaction_id' => $transactionId,
            'account_id' => $this->cashAccount->id,
            'type' => 'credit',
            'amount' => '150000.00',
        ]);

        // Assert attachment record exists
        $this->assertDatabaseHas('attachments', [
            'transaction_id' => $transactionId,
            'original_name' => 'invoice.jpg',
        ]);

        // Assert file is stored in public disk
        $attachment = $response->json('data.attachments.0');
        Storage::disk('public')->assertExists($attachment['file_path']);
    }

    /**
     * Test list of transactions, filters and cash flow calculations.
     */
    public function test_user_can_view_transactions_list_and_summaries(): void
    {
        // 1. Post Cash In transaction
        $this->actingAs($this->user)->postJson('/api/transactions', [
            'type' => 'in',
            'amount' => 500000.00,
            'account_id' => $this->revenueAccount->id, // Crediting Revenue
            'payment_account_id' => $this->cashAccount->id, // Debiting Kas Utama
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'Pendapatan jasa konsultasi',
        ]);

        // 2. Post Cash Out transaction
        $this->actingAs($this->user)->postJson('/api/transactions', [
            'type' => 'out',
            'amount' => 120000.00,
            'account_id' => $this->expenseAccount->id, // Debiting Expense
            'payment_account_id' => $this->cashAccount->id, // Crediting Kas Utama
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'Beli kopi rapat',
        ]);

        // 3. Fetch index
        $response = $this->actingAs($this->user)->getJson('/api/transactions');

        $response->assertStatus(200)
            ->assertJsonPath('summary.total_in', 500000)
            ->assertJsonPath('summary.total_out', 120000)
            ->assertJsonPath('summary.net_flow', 380000);

        $this->assertCount(2, $response->json('data'));
    }

    /**
     * Test updating a transaction.
     */
    public function test_user_can_update_transaction_recalculating_journal_entries(): void
    {
        // 1. Create initial transaction
        $createResponse = $this->actingAs($this->user)->postJson('/api/transactions', [
            'type' => 'out',
            'amount' => 100000.00,
            'account_id' => $this->expenseAccount->id,
            'payment_account_id' => $this->cashAccount->id,
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'Original Description',
        ]);
        $txId = $createResponse->json('data.id');

        // 2. Perform update
        $updateResponse = $this->actingAs($this->user)->putJson('/api/transactions/' . $txId, [
            'type' => 'out',
            'amount' => 250000.00, // Updated amount
            'account_id' => $this->expenseAccount->id,
            'payment_account_id' => $this->cashAccount->id,
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'Updated Description', // Updated description
        ]);

        $updateResponse->assertStatus(200)
            ->assertJsonPath('message', 'Transaction updated successfully.');

        // Assert database header is updated
        $this->assertDatabaseHas('transactions', [
            'id' => $txId,
            'description' => 'Updated Description',
        ]);

        // Assert old journal entries are deleted and new ones are inserted with updated amount
        $this->assertDatabaseHas('journal_entries', [
            'transaction_id' => $txId,
            'account_id' => $this->expenseAccount->id,
            'type' => 'debit',
            'amount' => '250000.00',
        ]);

        $this->assertDatabaseHas('journal_entries', [
            'transaction_id' => $txId,
            'account_id' => $this->cashAccount->id,
            'type' => 'credit',
            'amount' => '250000.00',
        ]);

        // Assert old 100000 journal entry is gone
        $this->assertDatabaseMissing('journal_entries', [
            'transaction_id' => $txId,
            'amount' => '100000.00',
        ]);
    }

    /**
     * Test deleting a transaction as an Owner.
     */
    public function test_owner_can_delete_transaction_cascading_and_deleting_files(): void
    {
        Storage::fake('public');

        $receipt = UploadedFile::fake()->image('receipt.jpg');

        // 1. Create transaction with attachment (as staff or owner)
        $createResponse = $this->actingAs($this->user)->postJson('/api/transactions', [
            'type' => 'out',
            'amount' => 50000.00,
            'account_id' => $this->expenseAccount->id,
            'payment_account_id' => $this->cashAccount->id,
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'To be deleted',
            'receipt' => $receipt,
        ]);
        $txId = $createResponse->json('data.id');
        $attachment = $createResponse->json('data.attachments.0');
        
        Storage::disk('public')->assertExists($attachment['file_path']);

        // 2. Perform delete as Owner
        $owner = User::factory()->create(['role' => 'owner']);
        $deleteResponse = $this->actingAs($owner)->deleteJson('/api/transactions/' . $txId);

        $deleteResponse->assertStatus(200)
            ->assertJsonPath('message', 'Transaction deleted successfully.');

        // Assert database cascade
        $this->assertDatabaseMissing('transactions', ['id' => $txId]);
        $this->assertDatabaseMissing('journal_entries', ['transaction_id' => $txId]);
        $this->assertDatabaseMissing('attachments', ['transaction_id' => $txId]);

        // Assert file is deleted from storage
        Storage::disk('public')->assertMissing($attachment['file_path']);
    }

    /**
     * Test that staff users are blocked from deleting transactions.
     */
    public function test_staff_cannot_delete_transaction(): void
    {
        // 1. Create transaction
        $createResponse = $this->actingAs($this->user)->postJson('/api/transactions', [
            'type' => 'out',
            'amount' => 50000.00,
            'account_id' => $this->expenseAccount->id,
            'payment_account_id' => $this->cashAccount->id,
            'transaction_date' => now()->format('Y-m-d'),
            'description' => 'Staff delete block test',
        ]);
        $txId = $createResponse->json('data.id');

        // 2. Try to delete as Staff (default $this->user)
        $deleteResponse = $this->actingAs($this->user)->deleteJson('/api/transactions/' . $txId);

        $deleteResponse->assertStatus(403)
            ->assertJsonPath('message', 'Akses Ditolak: Hanya Owner yang dapat menghapus transaksi.');

        // Assert transaction still exists
        $this->assertDatabaseHas('transactions', ['id' => $txId]);
    }
}
